version: '3.8'

services:

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: suivi_sante
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
# Uncomment the following lines to enable pgAdmin
  web:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db

## Uncomment the following lines to enable the cron service
  cron:
    build: ./cron
    depends_on:
      - web
    volumes:
      - ./backend:/app


volumes:
  pgdata:
